CREATE TABLE blogs (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    content TEXT NOT NULL,
    preview_image VARCHAR(255),
    header_image VARCHAR(255),
    published INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO blogs (title, subtitle, slug, preview_image, content) VALUES
                                                                      (
                                                                          'First Feedback',
                                                                          'The First Feedback I Got',
                                                                          'first-feedback',
                                                                          '/images/feedback.png',
                                                                          '<div class="row justify-content-center mt-4"><div class="row"><section class="col-md-8"><h3> Introduction </h3><p>This week I received my very first round of feedback on my PCO portfolio assignment, and it was a helpful check on what I need to polish up. The comments were split between front-end and back-end, which gave me a clear idea of what to tackle.</p><h4 class="mt-4"> Front-end improvements </h4><ul><li>Finish the blog pages (some were incomplete at the time of review).</li><li>Remove the default link decorations for a cleaner look.</li><li>Group the dashboard rows in the grade table so the layout feels more organized.</li></ul><h4 class="mt-4"> Back-end improvements </h4><ul><li>Add comments in the CSS to make the code easier to understand.</li><li>Store images properly in a dedicated folder instead of scattering them around.</li></ul><p class="mt-4">Overall, the feedback showed me that I was on the right track, but I still need to focus on small details that improve both usability and maintainability. I''m excited to work on these adjustments and see the portfolio evolve into something more polished and professional.</p></section><aside class="col-md-4"><img class="w-100 blog-images rounded" src="/images/poster.png" alt="My poster"></aside></div></div>'
                                                                      ),
                                                                      (
                                                                          'Game projects',
                                                                          'My Luau Game Projects',
                                                                          'fieldwork-ict',
                                                                          '/images/luau.png',
                                                                          '<div class="row justify-content-center mt-4"><h3> Learning Through Game Development </h3><p>A large part of my coding journey started with <strong>Luau</strong>, the scripting language of Roblox Studio. By experimenting with systems, mechanics, and player interaction, I learned how to structure code, solve problems, and bring ideas to life. These projects gave me practical experience that I''m now building on in web and software development.</p><h4 class="mt-4"> Some Things I Worked On </h4><ul><li><strong>Admin panel:</strong> A Roblox management system that lets admins control gameplay, store and modify player data, and use custom commands for fast in-game management.</li><li><strong>Whispered:</strong> An infinite exploration game with procedurally generated “chunks / biomes” and interactive items like consumables with unique effects.</li><li><strong>Minesweeper:</strong> A recreation of the classic puzzle game inside Roblox, using Luau scripting to handle grid logic, bomb placement, and reveal mechanics.</li><li><strong>BlockRunners (Spleef):</strong> A fast-paced multiplayer minigame where players try to survive by breaking blocks under opponents'' feet while keeping themselves safe.</li><li>Worked with <strong>DataStores</strong> to serialize and persist complex data like notes and metadata.</li></ul><h4 class="mt-4"> Skills I Gained </h4><ul><li>Building structured systems in an event-driven environment.</li><li>Hands-on experience with saving/loading persistent player data using Roblox DataStores.</li><li>Debugging and testing live multiplayer features.</li><li>Creativity in designing unique mechanics and environments that encourage exploration.</li><li>Designing both single-player puzzle logic and competitive multiplayer gameplay loops.</li></ul><p class="mt-4">These Luau projects were my introduction to development, and they showed me how much I enjoy creating interactive systems. From building management tools like my admin panel, to experimenting with infinite world generation in <em>Whispered</em>, or designing competitive games like <em>Minesweeper</em> and <em>BlockRunners</em>, I gained both technical and creative skills that I now apply to larger-scale web and software projects.</p></div>'
                                                                      ),
                                                                      (
                                                                          'SWOT Analysis',
                                                                          'My Personal Development Review',
                                                                          'swot-analysis',
                                                                          '/images/swot.png',
                                                                          '<div class="row justify-content-center mt-4"><div class="col-md-6"><article class="blog-block p-4"><h3>Strengths</h3><ul><li>Strong problem-solving mindset and analytical skills.</li><li>Organized coding style and attention to detail.</li><li>Experience with multiple languages (Java, SQL, Luau, JavaScript, etc.).</li><li>Creativity in both game and software design.</li></ul></article></div><div class="col-md-6"><article class="blog-block p-4"><h3>Weaknesses</h3><ul><li>Perfectionism can slow progress.</li><li>Still improving teamwork communication in large groups.</li><li>Distracted easily which can slow progress.</li></ul></article></div><div class="col-md-6 mt-4"><article class="blog-block p-4"><h3>Opportunities</h3><ul><li>Potential internships and networking in the software industry.</li><li>Solid foundation to branch into professional web & software development.</li></ul></article></div><div class="col-md-6 mt-4"><article class="blog-block p-4"><h3>Threats</h3><ul><li>Balancing school, projects, and personal growth could create time pressure.</li><li>Rapidly evolving technology skills risk becoming outdated without continuous learning.</li></ul></article></div></div>'
                                                                      ),
                                                                      (
                                                                          'Programming Experience',
                                                                          'How I Built My Skills',
                                                                          'programming-experience',
                                                                          '/images/java.png',
                                                                          '<section class="mt-4 container"><h3> Building Skills Through Real-World Experience </h3><p>My programming journey has taken me through internships, education, and personal projects. Each experience taught me something different whether it was working with hardware-integrated software, building cross-platform apps, or developing game systems. These opportunities shaped how I approach problem-solving and software development today.</p><h4 class="mt-4"> Key Experiences </h4><ul><li><strong>Internship at Epesi:</strong> Worked with FlutterFlow and Dart to build mobile a mobile app to track football game events, learning rapid prototyping and cross-platform development.</li><li><strong>Internship at Moduvision:</strong> Developed software in C# that interacted with autosamplers, gaining hands-on experience with hardware integration and technical debugging.</li><li><strong>MBO Education in Software Development:</strong> Built foundational projects like Pasimo, QR-Goats, and Slidehub using frameworks like Struts 2, Hibernate, and Bootstrap, working in team environments with Scrum methodology.</li><li><strong>Game Development with Roblox Studio:</strong> Created multiple games and systems using Luau, including admin panels, exploration games, and competitive multiplayer minigames, learning event-driven programming and DataStores.</li></ul><h4 class="mt-4"> Languages & Technologies </h4><ul><li><strong>Languages:</strong> Luau, C#, JavaScript, Java, Dart partially, SQL, HTML/CSS, PHP.</li><li><strong>Frameworks & Tools:</strong> FlutterFlow, Struts 2, Hibernate, Bootstrap.</li><li><strong>Development Tools:</strong> Roblox Studio, Eclipse IDE, VSCode, MySQL Workbench, InteliJ</li><li><strong>Methodologies:</strong> Scrum, version control, debugging, and testing in both solo and team environments</li></ul><p class="mt-4">From working on cross-platform mobile apps to building hardware-integrated software and creating multiplayer games, these experiences gave me a diverse skill set. I learned to adapt to different languages and environments, collaborate with teams, and solve complex technical challenges. This foundation continues to drive my growth as a developer.</p></section>'
                                                                      ),
                                                                      (
                                                                          'Study Choice',
                                                                          'Why I Chose HBO',
                                                                          'study-choice',
                                                                          '/images/hz-logo.png',
                                                                          '<section class="mt-4 container"><h3> From MBO to HBO </h3><p>After completing my <strong>MBO in Software Development</strong>, choosing to continue to HBO felt like the natural next step. My MBO experience gave me a solid foundation in programming, teamwork, and practical project work and I genuinely enjoyed it. I learned a lot, built real applications, and discovered that software development was something I wanted to keep pursuing.</p><h4 class="mt-4"> Why HBO? </h4><ul><li><strong>Building on what I know:</strong> My MBO background prepared me well for HBO-level work. I already understood the basics and wanted to deepen that knowledge.</li><li><strong>Passion for development:</strong> Between my education and my game development projects in Roblox Studio, I realized how much I enjoy creating systems, solving problems, and building interactive experiences.</li><li><strong>Career growth:</strong> An HBO diploma opens more doors professionally. It gives me access to more opportunities, better positions, and the chance to work on larger, more complex projects.</li><li><strong>Continuing the journey:</strong> I wanted to keep learning and growing as a developer. HBO lets me go deeper into software engineering, explore new technologies, and refine my skills.</li></ul><p class="mt-4">Choosing HBO wasn''t just about getting a higher diploma, it was about continuing to do what I love and setting myself up for a successful career in software development. I enjoyed my time at MBO, learned a ton from my game projects, and now I''m ready to take on the next challenge and keep building my expertise.</p></section>'
                                                                      );UPDATE blogs SET published = 1;
