name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan
        run: php maestro phpstan

      - name: Run PHPCS
        run: php maestro phpcs

      - name: Run Deptrac
        run: php maestro deptrac

      - name: Install Railway CLI
        if: success()
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        if: success()
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }} --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}